name: Update locale files

on:
  pull_request:
    branches: [main, master]
    paths:
      - "**.lua"

jobs:
  gettext:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install gettext
        run: sudo apt install gettext

      - name: Update locale files
        run: |
          mkdir -p locale

          # Update .pot file
          find . -type f -name "*.lua" | sort | xgettext -L lua \
            --add-location \
            -kS -kPS:1,2 -kcore.translate:1c,2 -kcore.translate_n:1c,2,3 \
            -d "${{ github.event.repository.name }}" \
            -o "locale/${{ github.event.repository.name }}.pot" \
            -f -

          # Update .po files
          if [ -f "locale/${{ github.event.repository.name }}.pot" ]; then
            for po_file in locale/*.po; do
              [ -f "$po_file" ] || continue
              msgmerge --backup=none --update "$po_file" "locale/${{ github.event.repository.name }}.pot"
            done
          fi

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add locale/

          CHANGES=$(git diff --cached --unified=0 locale/ | grep -E "^[+-][^+-]" | grep -E -v "^[+-]\"POT-Creation-Date:" || true)

          if [ -n "$CHANGES" ]; then
            git commit -m "[ci] Update locale files"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No files modified."
          fi
